# Generated by Django 5.0.6 on 2024-07-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_description_todo_title_remove_todo_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_date',
            new_name='date',
        ),
    ]
