# Generated by Django 4.2.11 on 2024-07-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
