# Generated by Django 4.2.11 on 2024-07-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
    ]
